version: "3.8"
services:
  gofirstdebug: #docker run -it -v ${PWD}:/go/src/work -v ${PWD}/golang/configs/:/configs -v ${PWD}/golang/secrets/:/secrets  -p 5001:5000 -p 2345:2345 --security-opt "seccomp:unconfined" aimvector/golang:1.0.0
    container_name: gofirstdebug
    image: jeff22ndtech/go-first:debug
    build: 
      context: .
      target: debug
    volumes:
    - ./:/src/work/ # Only set this for debug
    ports:
      - 9091:9090
      - 2345:2345
    security_opt: # Only set this for debug
      - "seccomp:unconfined"