---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: go-first
  name: go-first
spec:
  containers:
    - image: 22ndtech/go-first
      name: go-first
      ports:
        - containerPort: 9091
          protocol: TCP
      resources:
        limits:
          cpu: "500m"
          memory: "128Mi"
        requests:
          cpu: "250m"
          memory: "64Mi"
      securityContext:
          privileged: true
