---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: go-first
  name: go-first
spec:
  containers:
    - image: 22ndtech/go-first:debug
      name: go-first
      ports:
        - containerPort: 2345
          protocol: TCP
        - containerPort: 9091
          protocol: TCP
      resources:
        limits:
          cpu: "500m"
          memory: "512Mi"
        requests:
          cpu: "250m"
          memory: "256Mi"
      securityContext:
          privileged: true